cf-vars:
  sys_domain: ((pas-domain))
  apps_domain: ((pas-domain))
  mysql-email: test@test.com
  credhub-key01: ((credkey01))
  network-name: PCF-Network

pas-version: 2.4.9
api-token: ((vponnam-api-token))
