---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/vponnam/platform-automations.git
    branch: dev

jobs:
- name: Create-OM
  plan:
  - get: src
  - task: create-iaas-and-om
    params:
      USER: ((user))
      LOCATION: ((location))
      OPS_MAN_IMAGE_URL: ((om-url))
      OM_VERSION: ((om-version))
      NSG_NAME: ((nsg)) 
      NETWORK: ((network))
      SUBNET: ((subnet))
      OM_IP: ((om-ip))
      OM_DISK: ((om-disk))
      OM_NIC: ((om-nic))
      PAS_PUB_IP: ((pas-ip))
      SSH_KEY_PATH: ((om-ssh-public))
      app_id: ((azure-client-id))
      client_secret: ((azure-client-secret))
      tenant: ((azure-tenant-id))
      VAULT_TOKEN: ((vault-token))
      VAULT_ADDR: ((vault-addr))
      VAULT_SKIP_VERIFY: ((vault-ssl))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vponnam/pipelines}
      inputs:
      - name: src
      run:
        path: src/az/iaas-provision/create-iaas.sh

- name: Vault-Creds
  plan:
  - get: src
  - task: write-vault-secrets
    params:
      VAULT_TOKEN: ((vault-token))
      VAULT_ADDR: ((vault-addr))
      VAULT_SKIP_VERIFY: ((vault-ssl))
      USER: ((user))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vponnam/pipelines}
      inputs:
      - name: src
      run:
        path: src/az/iaas-provision/write-vault-secrets.sh
 
- name: Configure-Director
  plan:
  - get: src
  - task: configure-director
    params:
      env: ((environment))
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source: {repository: vponnam/pipelines}
      inputs: 
      - name: src
      run:
        path: bash
        args:
        - -exc
        - |
          bosh int `echo $env` > env.yml
          om --env env.yml configure-authentication
