---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/vponnam/platform-automations.git
    branch: dev

jobs:
- name: Delete-OM
  plan:
  - get: src
  - task: delete-pcf-installation
    params
  - task: delete-iaas-and-om
    params:
      USER: ((user))
      LOCATION: ((location))
      OPS_MAN_IMAGE_URL: ((om-url))
      OM_VERSION: ((om-version))
      NSG_NAME: ((nsg)) 
      NETWORK: ((network))
      SUBNET: ((subnet))
      OM_IP: ((om-ip))
      OM_DISK: ((om-disk))
      OM_NIC: ((om-nic))
      PAS_PUB_IP: ((pas-ip))
      app_id: ((azure-client-id))
      client_secret: ((azure-client-secret))
      tenant: ((azure-tenant-id))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: vponnam/pipelines}
      inputs:
      - name: src
      run:
        path: src/az/iaas-provision/delete-iaas.sh
